freebsd_14_task:
  freebsd_instance:
    image: freebsd-14-1-release-amd64-ufs
    cpu: 2
    memory: 3G
  env:
    CIRRUS_CLONE_DEPTH: 1
  install_script: pkg install -y curl gcc git glib gmake cmake gnutls pkgconf libX11
  script:
    - export CC=gcc
    - export CXX=g++
    - cd CMAKE
    - cmake -H. -Bbuild
    - cmake --build build -- -j2

#osx_task:
#  osx_instance:
#    image: catalina-base
#  env:
#    CIRRUS_CLONE_DEPTH: 1
#  install_script:
#    - brew install gcc cmake
#    - curl -L -O https://github.com/pgp/BinRels/releases/download/bin-xqtz2711/xqtz.zip
#    - unzip xqtz.zip
#    - hdiutil mount XQuartz-2.7.11.dmg
#    - sudo installer -store -pkg /Volumes/XQuartz-2.7.11/XQuartz.pkg -target /
#    - hdiutil unmount /Volumes/XQuartz-2.7.11
#  script:
#    - export CC=gcc-10
#    - export CXX=g++-10
#    - cd CMAKE
#    - cmake -H. -Bbuild
#    - cmake --build build -- -j1

linux_task:
  container:
    image: openjdk:8-jdk
  env:
    CIRRUS_CLONE_DEPTH: 1
  install_script:
    - apt update
    - apt install -y gcc g++ cmake libx11-dev
  script:
    - export CC=gcc
    - export CXX=g++
    - cd CMAKE
    - cmake -H. -Bbuild
    - cmake --build build -- -j1
