language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
            - libx11-dev
      env:
         - TARGETTING_ANDROID=false
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && cd CMAKE && cmake -H. -Bbuild" 
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - TARGETTING_ANDROID=true
         - MATRIX_EVAL="" 

    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - gcc@8
            - cmake
      env:
        - TARGETTING_ANDROID=false
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8 && cd CMAKE && cmake -H. -Bbuild"

    - os: windows
      addons:
        chocolatey:
          packages:
            - mingw
            - cmake
      env:
        - TARGETTING_ANDROID=false
        - MATRIX_EVAL="export CC=gcc && export CXX=g++ && cd CMAKE && cmake -G \"MinGW Makefiles\" -DCMAKE_SH=\"CMAKE_SH-NOTFOUND\" -H. -Bbuild"

before_script:
  - eval "${MATRIX_EVAL}"

script:
- if $TARGETTING_ANDROID; then source ./genRootHelpersAndroid_travis.sh;
  else cmake --build build -- -j4; fi
